# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty
language: generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - g++-5
            - clang-3.8
          sources: 
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - hdf5-tools 
            - libhdf5-dev
            - sqlite3 
            - libsqlite3-dev 
            - libsqlite3-0

before_install:
  - sudo apt-get update -qq
script:
  - cmake . 
  - make VERBOSE=1
  - cd test && ctest

notifications:
   email: false
